name: "Setup"
description: "Setup"
runs:
  using: "composite"
  steps:
      - run: sudo apt-get update
        shell: bash
      - run: sudo apt-get install -y pkg-config build-essential libudev-dev
        shell: bash
      - run: echo "ANCHOR_VERSION=0.24.2" >> $GITHUB_ENV
        shell: bash
      - run: git submodule update --init --recursive --depth 1
        shell: bash
